export const itineraryData = [
  {
    day: 1,
    date: '16 Agosto',
    title: 'Arrivo a Keflavík → Reykjavík',
    locations: ['Keflavík International Airport', 'Reykjavík'],
    coordinates: [64.1466, -21.9426],
    activities: [
      {
        name: 'Atterraggio a KEF e ritiro auto',
        time: '18:50 + formalità',
        description:
          'Arrivo a Keflavík, ritiro dell’auto a noleggio e trasferimento verso Reykjavík su strada semplice, asfaltata e lineare.',
        highlights: ['Tragitto facile', 'Nessun tratto esposto', 'Perfetto per iniziare senza stress'],
      },
      {
        name: 'Passeggiata rilassata in centro',
        time: 'Sera',
        description:
          'Cena, breve passeggiata in centro oppure check-in diretto e riposo. La prima sera è volutamente leggera.',
        notes: 'Con un arrivo serale conviene non caricare troppo il programma.',
      },
    ],
    accommodation: 'Reykjavík – 1 notte',
    distance: '~50 km / 45 min',
    antiVertigoNotes:
      'Strade larghe e scorrevoli: inizio ideale per chi vuole evitare percorsi stressanti o panorami troppo esposti.',
    tips: [
      'Controlla bene gomme, parabrezza e danni al ritiro auto.',
      'Se l’hotel è in centro, verifica la zona parcheggio.',
      'Prima notte volutamente soft per partire bene il giorno dopo.',
    ],
  },
  {
    day: 2,
    date: '17 Agosto',
    title: 'Golden Circle',
    locations: ['Thingvellir National Park', 'Geysir', 'Gullfoss Falls', 'Secret Lagoon'],
    coordinates: [64.3271, -20.1211],
    activities: [
      {
        name: 'Thingvellir National Park',
        time: 'Mattina',
        description:
          'Parco nazionale UNESCO dove si incontrano le placche tettoniche nordamericana ed eurasiatica. Sentieri larghi e visuali aperte.',
        highlights: ['Almannagjá', 'Paesaggi aperti', 'Sito storico islandese'],
        notes: 'Ottimo primo grande stop del viaggio: molto suggestivo ma gestibile.',
      },
      {
        name: 'Geysir e Strokkur',
        time: 'Metà giornata',
        description:
          'Area geotermale iconica con Strokkur che erutta regolarmente. Visita brevissima, quasi pianeggiante e molto facile.',
        price: 'Gratuito',
        highlights: ['Eruzioni ogni 5–10 minuti', 'Pozze geotermali', 'Stop semplice e memorabile'],
      },
      {
        name: 'Gullfoss Falls',
        time: 'Pomeriggio',
        description:
          'Una delle cascate più famose d’Islanda. Restando sulle piattaforme superiori la visita resta comoda e panoramica.',
        highlights: ['Vista iconica', 'Piattaforme sicure', 'Arcobaleni nelle giornate di sole'],
        notes: 'Il tratto più vicino alla cascata è facoltativo.',
      },
      {
        name: 'Secret Lagoon (facoltativa)',
        time: 'Fine giornata',
        description:
          'Bagno termale semplice e rilassante a Flúðir, perfetto per chiudere il Golden Circle senza fretta.',
        price: '~4.000 ISK a persona',
      },
    ],
    accommodation: 'Hella / Hvolsvöllur',
    distance: '3–4 ore di guida totali',
    antiVertigoNotes:
      'Tappe molto adatte: strade semplici, punti panoramici ampi, nessun tratto davvero problematico.',
    tips: [
      'Partire presto da Reykjavík aiuta a fare tutto con calma.',
      'Pranzo nell’area di Geysir oppure snack al sacco.',
      'Dormire già verso Hella o Hvolsvöllur rende il giorno 3 più comodo.',
    ],
  },
  {
    day: 3,
    date: '18 Agosto',
    title: 'Costa Sud fino a Vík',
    locations: ['Seljalandsfoss', 'Skógafoss', 'Dyrhólaey', 'Reynisfjara Beach', 'Vík'],
    coordinates: [63.4186, -19.006],
    activities: [
      {
        name: 'Seljalandsfoss',
        time: 'Mattina',
        description:
          'Cascata iconica alta 60 metri. Il giro dietro la cascata è facoltativo: già dalla parte frontale è stupenda.',
        highlights: ['Vista frontale spettacolare', 'Stop semplice', 'Gljúfrabúi nelle vicinanze'],
      },
      {
        name: 'Skógafoss',
        time: 'Metà giornata',
        description:
          'Grande cascata rettilinea e potentissima. La base offre già la visuale migliore; la lunga scalinata è facoltativa.',
        highlights: ['Cascata simbolo', 'Arcobaleni frequenti', 'Perfetta anche senza salire'],
        notes: 'Se le scale o i punti alti non ti piacciono, fermati serenamente alla base.',
      },
      {
        name: 'Dyrhólaey (facoltativo)',
        time: 'Pomeriggio',
        description:
          'Punto panoramico molto bello sulla costa sud. Si può saltare senza problemi se scogliere, vento o esposizione non ti fanno stare bene.',
        highlights: ['Vista oceano', 'Arco naturale', 'Totalmente opzionale'],
        notes: 'In un itinerario anti-vertigini è una delle tappe più facilmente sacrificabili.',
      },
      {
        name: 'Reynisfjara Beach',
        time: 'Pomeriggio',
        description:
          'Spiaggia nera famosissima con colonne di basalto e faraglioni Reynisdrangar.',
        price: 'Gratuito',
        highlights: ['Basalto nero', 'Faraglioni in mare', 'Paesaggio vulcanico unico'],
        warning:
          'Sneaker waves: non avvicinarsi all’acqua e non voltare mai le spalle al mare.',
      },
      {
        name: 'Vík í Mýrdal',
        time: 'Sera',
        description:
          'Piccolo villaggio comodissimo per cena e pernottamento, perfetto per spezzare bene la Costa Sud.',
      },
    ],
    accommodation: 'Vík – 1 notte',
    distance: '2–3 ore di guida + soste',
    antiVertigoNotes:
      'Giornata ottima. Dyrhólaey resta facoltativo proprio per mantenere il viaggio confortevole.',
    tips: [
      'Porta giacca impermeabile: Seljalandsfoss bagna facilmente.',
      'A Reynisfjara state molto indietro rispetto all’acqua.',
      'Vík è una base strategica e riposante.',
    ],
  },
  {
    day: 4,
    date: '19 Agosto',
    title: 'Vík → Jökulsárlón',
    locations: ['Fjaðrárgljúfur', 'Skaftafell', 'Jökulsárlón', 'Diamond Beach'],
    coordinates: [64.0489, -16.1798],
    activities: [
      {
        name: 'Fjaðrárgljúfur (facoltativo)',
        time: 'Mattina',
        description:
          'Canyon molto scenografico. Se preferisci evitare affacci o punti troppo esposti, puoi saltarlo tranquillamente.',
        highlights: ['Stop verde e fotogenico', 'Passeggiata breve', 'Facoltativo'],
        notes: 'In un piano anti-vertigini è uno degli stop più sacrificabili.',
      },
      {
        name: 'Skaftafell',
        time: 'Metà giornata',
        description:
          'Area del Vatnajökull National Park con paesaggi glaciali, centro visitatori e possibilità di camminate semplici.',
        highlights: ['Parco nazionale', 'Sentieri comodi', 'Grande pausa panoramica'],
      },
      {
        name: 'Jökulsárlón Glacier Lagoon',
        time: 'Pomeriggio',
        description:
          'Laguna glaciale con iceberg galleggianti e spesso foche visibili. Uno dei luoghi più spettacolari del viaggio.',
        price: 'Ingresso gratuito | Boat tour facoltativo',
        highlights: ['Iceberg blu e bianchi', 'Possibili foche', 'Visita semplice e spettacolare'],
      },
      {
        name: 'Diamond Beach',
        time: 'Subito dopo Jökulsárlón',
        description:
          'Sulla spiaggia nera arrivano blocchi di ghiaccio che sembrano diamanti.',
        highlights: ['Contrasto ghiaccio-sabbia nera', 'Foto memorabili', 'Passeggiata semplice'],
      },
    ],
    accommodation: 'Zona Jökulsárlón / Höfn',
    distance: 'Circa 2,5 ore di guida',
    antiVertigoNotes:
      'Tra le giornate migliori per questo tipo di viaggio: paesaggi ampi, stop facili e quasi nessun punto davvero esposto.',
    tips: [
      'Se vuoi il boat tour prenotalo in anticipo.',
      'Anche senza tour, la laguna è già uno dei grandi highlight del viaggio.',
      'Se non vuoi allungare troppo, dormire vicino alla laguna è perfetto.',
    ],
  },
  {
    day: 5,
    date: '20 Agosto',
    title: 'Ritorno verso ovest con calma',
    locations: ['Skaftafell', 'Kirkjubæjarklaustur', 'Vík'],
    coordinates: [63.7833, -18.0667],
    activities: [
      {
        name: 'Rientro rilassato lungo la Costa Sud',
        time: 'Tutto il giorno',
        description:
          'Giornata pensata per non fare un rientro massacrante in un colpo solo. Spazio per fermarsi meglio dove serve.',
        highlights: ['Guida spezzata', 'Più relax', 'Possibilità di recuperare stop saltati'],
      },
      {
        name: 'Soste libere / breve passeggiata a Skaftafell',
        time: 'Flessibile',
        description:
          'Se all’andata avete corso un po’, oggi potete prendervela con calma e recuperare uno o due stop con più qualità.',
        notes: 'Questa giornata è il cuore del ritmo rilassato dell’itinerario.',
      },
    ],
    accommodation: 'Vík o Kirkjubæjarklaustur',
    distance: '4–5 ore spezzate',
    antiVertigoNotes:
      'Nessuna tappa estrema: lo scopo è ridurre stanchezza e mantenere il viaggio piacevole.',
    tips: [
      'Meglio meno tappe ma fatte bene.',
      'Decidi il pernottamento in base a quanto vuoi davvero guidare.',
      'Cena presto e serata tranquilla.',
    ],
  },
  {
    day: 6,
    date: '21 Agosto',
    title: 'Costa Sud → Snæfellsnes con pausa a Reykjavík',
    locations: ['Reykjavík', 'Stykkishólmur', 'Grundarfjörður'],
    coordinates: [64.9267, -23.3065],
    activities: [
      {
        name: 'Rientro verso Reykjavík',
        time: 'Mattina',
        description:
          'Prima parte del trasferimento verso ovest, con pausa pranzo o caffè in città per spezzare bene la giornata.',
        highlights: ['Guida divisa in due', 'Pausa vera', 'Ritmo più sostenibile'],
      },
      {
        name: 'Proseguimento per Snæfellsnes',
        time: 'Pomeriggio',
        description:
          'Seconda parte del trasferimento verso la penisola di Snæfellsnes, una delle zone più scenografiche ma generalmente facili da guidare.',
        notes: 'Arrivare già il 21 permette di non comprimere tutto nel giorno 7.',
      },
    ],
    accommodation: 'Grundarfjörður – 1 notte',
    distance: '5–6 ore totali divise in due',
    antiVertigoNotes:
      'Strada più lunga ma resa molto più sostenibile grazie alla pausa a Reykjavík.',
    tips: [
      'Non correre: la logica di questa giornata è spezzare il trasferimento.',
      'Grundarfjörður è comoda per Kirkjufell.',
      'Se siete stanchi, anche Borgarnes può funzionare come piano B.',
    ],
  },
  {
    day: 7,
    date: '22 Agosto',
    title: 'Snæfellsnes Peninsula → Keflavík',
    locations: ['Kirkjufell', 'Arnarstapi', 'Búðakirkja', 'Djúpalónssandur beach', 'Keflavík'],
    coordinates: [64.821, -23.3847],
    activities: [
      {
        name: 'Kirkjufell',
        time: 'Mattina',
        description:
          'La montagna più fotografata d’Islanda, perfetta per uno stop iconico ma facile e rapido.',
        highlights: ['Foto celebre', 'Kirkjufellsfoss accanto', 'Stop super accessibile'],
      },
      {
        name: 'Arnarstapi',
        time: 'Metà giornata',
        description:
          'Villaggio costiero con scogliere basaltiche e sentieri panoramici. Le parti più esposte si possono evitare.',
        highlights: ['Archi di roccia', 'Costa vulcanica', 'Passeggiata modulabile'],
        notes: 'Se c’è vento forte, limitati ai punti più ampi.',
      },
      {
        name: 'Búðakirkja',
        time: 'Stop breve',
        description:
          'Celebre chiesa nera isolata in un paesaggio aperto e minimalista.',
        highlights: ['Chiesa nera iconica', 'Foto eleganti', 'Sosta breve'],
      },
      {
        name: 'Djúpalónssandur',
        time: 'Pomeriggio',
        description:
          'Spiaggia vulcanica con ciottoli neri, relitti storici e atmosfera quasi lunare.',
        highlights: ['Spiaggia scura', 'Relitti', 'Scenario molto diverso dalla Costa Sud'],
      },
      {
        name: 'Rientro verso Keflavík',
        time: 'Sera',
        description:
          'Ultimo trasferimento e pernottamento vicino all’aeroporto per rendere facilissima la partenza del mattino seguente.',
      },
    ],
    accommodation: 'Keflavík / area aeroporto',
    distance: 'Giornata piena ma gestibile',
    antiVertigoNotes:
      'Snæfellsnes resta bellissima anche evitando i punti che ti mettono a disagio: nulla è obbligatorio.',
    tips: [
      'Kirkjufell è il must assoluto della penisola.',
      'Ad Arnarstapi scegli i tratti più larghi se c’è vento.',
      'Dormire vicino a KEF è la soluzione migliore con il volo delle 08:20.',
    ],
  },
  {
    day: 8,
    date: '23 Agosto',
    title: 'Partenza',
    locations: ['Keflavík International Airport'],
    coordinates: [63.985, -22.6056],
    activities: [
      {
        name: 'Restituzione auto e check-in',
        time: '05:30–05:45 arrivo in aeroporto',
        description:
          'Riconsegna auto, check-in e controlli per il volo delle 08:20.',
        highlights: ['Logistica semplice', 'Partenza senza stress'],
      },
    ],
    accommodation: '—',
    distance: 'Trasferimento breve',
    antiVertigoNotes: 'Solo logistica finale: nessun tratto problematico.',
    tips: [
      'Fai il pieno la sera prima se richiesto dal noleggio.',
      'Con un volo mattutino conviene davvero dormire vicino a KEF.',
      'Tieni pronti documenti e conferma del noleggio.',
    ],
  },
];

export const mapPoints = [
  {
    day: 1,
    type: 'day-1',
    name: 'Keflavík International Airport',
    lat: 63.985,
    lng: -22.6056,
    address: '235 Keflavík, Iceland',
    description: 'Aeroporto internazionale principale dell’Islanda e punto di ritiro auto.',
    special: 'Ti permette di iniziare il viaggio in autonomia senza spostamenti complicati.',
    price: 'Fonte mappa: Google Maps',
  },
  {
    day: 1,
    type: 'day-1',
    name: 'Reykjavík',
    lat: 64.1466,
    lng: -21.9426,
    address: '101 Reykjavík, Iceland',
    description: 'Capitale islandese e base ideale per la prima notte.',
    special: 'Perfetta per iniziare con calma: città compatta, passeggiata facile e ottima scelta di hotel.',
  },
  {
    day: 2,
    type: 'day-2',
    name: 'Thingvellir National Park',
    lat: 64.2558,
    lng: -21.1292,
    address: '806 Selfoss, Iceland',
    description: 'Parco nazionale UNESCO dove si incontrano le placche tettoniche.',
    special: 'Sentieri larghi e visuali ampie: uno dei luoghi più adatti in chiave anti-vertigini.',
  },
  {
    day: 2,
    type: 'day-2',
    name: 'Geysir',
    lat: 64.3104,
    lng: -20.3024,
    address: '806, Iceland',
    description: 'Area geotermale con Strokkur che erutta regolarmente.',
    special: 'Stop facile, breve e spettacolare grazie alle eruzioni frequenti.',
  },
  {
    day: 2,
    type: 'day-2',
    name: 'Gullfoss Falls',
    lat: 64.3271,
    lng: -20.1211,
    address: '846, Iceland',
    description: 'Una delle cascate più famose d’Islanda.',
    special: 'Le piattaforme superiori danno una vista magnifica restando in una zona più semplice e sicura.',
  },
  {
    day: 2,
    type: 'day-2',
    name: 'Secret Lagoon',
    lat: 64.1403,
    lng: -20.3095,
    address: 'Hvammsvegur, 845 Flúðir, Iceland',
    description: 'Piccola laguna termale storica a Flúðir.',
    special: 'Alternativa rilassata alle lagune più turistiche, ideale a fine Golden Circle.',
    price: 'Facoltativa',
  },
  {
    day: 3,
    type: 'day-3',
    name: 'Seljalandsfoss',
    lat: 63.6156,
    lng: -19.9886,
    address: '861, Iceland',
    description: 'Cascata alta 60 metri famosa per il sentiero che le gira dietro.',
    special: 'Anche senza fare il giro completo, la vista frontale è già eccezionale.',
  },
  {
    day: 3,
    type: 'day-3',
    name: 'Skógafoss',
    lat: 63.5321,
    lng: -19.5114,
    address: '861, Iceland',
    description: 'Grande cascata rettilinea e uno dei simboli del sud dell’Islanda.',
    special: 'Bellissima dalla base, quindi perfetta anche evitando la scala panoramica.',
  },
  {
    day: 3,
    type: 'day-3',
    name: 'Dyrhólaey',
    lat: 63.3996,
    lng: -19.1269,
    address: '218 Dyrhólaey, Iceland',
    description: 'Promontorio panoramico sulla costa sud.',
    special: 'La vista è bellissima, ma è completamente opzionale in un itinerario anti-vertigini.',
    price: 'Facoltativo',
  },
  {
    day: 3,
    type: 'day-3',
    name: 'Reynisfjara Beach',
    lat: 63.4042,
    lng: -19.0445,
    address: 'Iceland',
    description: 'Spiaggia nera con colonne di basalto e faraglioni Reynisdrangar.',
    special: 'Tra i luoghi più iconici del paese, ma va vissuta con prudenza per le sneaker waves.',
    price: 'Attenzione massima al mare',
  },
  {
    day: 3,
    type: 'day-3',
    name: 'Vík',
    lat: 63.4186,
    lng: -19.006,
    address: '870, Iceland',
    description: 'Villaggio della costa sud perfetto come base per la notte.',
    special: 'Spezza benissimo il percorso e rende la giornata molto più comoda.',
  },
  {
    day: 4,
    type: 'day-4',
    name: 'Fjaðrárgljúfur',
    lat: 63.7711,
    lng: -18.1715,
    address: 'Fjaðrárgljúfur, 880 Kirkjubæjarklaustur, Iceland',
    description: 'Canyon verde molto scenografico a est di Vík.',
    special: 'Bello per le foto, ma facilmente saltabile se preferisci evitare affacci.',
    price: 'Facoltativo',
  },
  {
    day: 4,
    type: 'day-4',
    name: 'Skaftafell',
    lat: 64.0159,
    lng: -16.9667,
    address: '785 Skaftafell, Iceland',
    description: 'Area del Vatnajökull National Park con sentieri e paesaggi glaciali.',
    special: 'Ottimo stop rilassato lungo il tragitto verso Jökulsárlón.',
  },
  {
    day: 4,
    type: 'day-4',
    name: 'Jökulsárlón',
    lat: 64.0489,
    lng: -16.1798,
    address: '781, Iceland',
    description: 'Laguna glaciale con iceberg galleggianti.',
    special: 'È uno dei posti più spettacolari del viaggio e anche tra i più facili da visitare.',
  },
  {
    day: 4,
    type: 'day-4',
    name: 'Diamond Beach',
    lat: 64.0442,
    lng: -16.1788,
    address: '781, Iceland',
    description: 'Spiaggia nera dove si posano blocchi di ghiaccio trasparente.',
    special: 'Il contrasto tra ghiaccio e sabbia vulcanica è unico e molto fotogenico.',
  },
  {
    day: 5,
    type: 'day-5',
    name: 'Kirkjubæjarklaustur',
    lat: 63.7833,
    lng: -18.0667,
    address: '880 Kirkjubæjarklaustur, Iceland',
    description: 'Piccolo centro strategico lungo la Costa Sud.',
    special: 'Perfetto per spezzare il rientro verso ovest in una giornata più morbida.',
  },
  {
    day: 5,
    type: 'day-5',
    name: 'Vík',
    lat: 63.4186,
    lng: -19.006,
    address: '870, Iceland',
    description: 'Possibile base anche per il secondo pernottamento sulla Costa Sud.',
    special: 'Mantiene il viaggio rilassato evitando un rientro eccessivamente lungo.',
  },
  {
    day: 6,
    type: 'day-6',
    name: 'Reykjavík',
    lat: 64.1466,
    lng: -21.9426,
    address: '101 Reykjavík, Iceland',
    description: 'Pausa strategica tra Costa Sud e Snæfellsnes.',
    special: 'Serve a dividere in due una delle tratte più lunghe del viaggio.',
  },
  {
    day: 6,
    type: 'day-6',
    name: 'Stykkishólmur',
    lat: 65.0753,
    lng: -22.7297,
    address: '340 Stykkishólmur, Iceland',
    description: 'Una delle possibili basi o tappe lungo la penisola di Snæfellsnes.',
    special: 'Ti porta già nel cuore della penisola senza concentrare tutto nel giorno 7.',
  },
  {
    day: 6,
    type: 'day-6',
    name: 'Grundarfjörður',
    lat: 64.9249,
    lng: -23.2592,
    address: '350 Grundarfjörður, Iceland',
    description: 'Base ideale per dormire vicino a Kirkjufell.',
    special: 'Ottima scelta logistica per iniziare bene la visita di Snæfellsnes.',
  },
  {
    day: 7,
    type: 'day-7',
    name: 'Kirkjufell',
    lat: 64.9267,
    lng: -23.3065,
    address: '351, Iceland',
    description: 'Montagna più fotografata d’Islanda, vicino a Grundarfjörður.',
    special: 'Stop iconico e facilissimo: uno dei migliori rapporti tra bellezza e semplicità del viaggio.',
  },
  {
    day: 7,
    type: 'day-7',
    name: 'Arnarstapi',
    lat: 64.7686,
    lng: -23.6207,
    address: 'Arnarstapi, Iceland',
    description: 'Villaggio costiero con archi di roccia e scogliere basaltiche.',
    special: 'Paesaggio incredibile, ma puoi godertelo scegliendo soltanto i tratti più comodi.',
  },
  {
    day: 7,
    type: 'day-7',
    name: 'Búðakirkja',
    lat: 64.821,
    lng: -23.3847,
    address: '356 Búðir, Iceland',
    description: 'Famosa chiesa nera isolata in un paesaggio aperto.',
    special: 'È uno stop breve ma elegantissimo, perfetto da inserire senza fatica.',
  },
  {
    day: 7,
    type: 'day-7',
    name: 'Djúpalónssandur beach',
    lat: 64.7519,
    lng: -23.8957,
    address: 'Unnamed Road Iceland, 356, Iceland',
    description: 'Spiaggia di ciottoli neri con relitti e paesaggio vulcanico.',
    special: 'Molto diversa dal resto del viaggio, con un’atmosfera quasi lunare.',
  },
  {
    day: 7,
    type: 'day-7',
    name: 'Keflavík',
    lat: 64.0049,
    lng: -22.5624,
    address: '230 Keflavík, Iceland',
    description: 'Zona migliore per l’ultima notte prima del volo.',
    special: 'Ti evita una partenza all’alba troppo pesante e rende semplice la restituzione auto.',
  },
  {
    day: 8,
    type: 'day-8',
    name: 'Keflavík International Airport',
    lat: 63.985,
    lng: -22.6056,
    address: '235 Keflavík, Iceland',
    description: 'Aeroporto di partenza per il rientro.',
    special: 'Chiusura logistica semplice del viaggio.',
  },
];

export const budgetData = {
  comfortFurbo: {
    name: 'Comfort Furbo',
    description: 'Guesthouse curate + qualche cena fuori',
    items: {
      voli: { min: 1000, max: 1800, note: 'Coppia A/R in alta stagione' },
      auto: { min: 700, max: 1300, note: '2WD automatico + coperture base o intermedie' },
      carburante: { min: 200, max: 350, note: 'Stima per itinerario Golden Circle + South Coast + Snæfellsnes' },
      alloggi: { min: 1400, max: 2400, note: '7 notti tra Reykjavík, Costa Sud, est e penisola' },
      pasti: { min: 600, max: 1000, note: 'Mix supermercato + qualche ristorante' },
      esperienze: { min: 250, max: 700, note: 'Facoltative: Secret Lagoon, boat tour, eventuale Sky Lagoon' },
    },
    total: { min: 4300, max: 7550 },
  },
  piuComodo: {
    name: 'Più Comodo',
    description: 'Hotel medi + più cene fuori + qualche extra',
    items: {
      voli: { min: 1200, max: 1800, note: 'Coppia A/R' },
      auto: { min: 900, max: 1300, note: 'Auto più comoda o coperture migliori' },
      carburante: { min: 250, max: 350, note: 'Simile alla fascia comfort' },
      alloggi: { min: 2000, max: 3500, note: 'Camere migliori e qualche hotel 4★' },
      pasti: { min: 900, max: 1400, note: 'Più ristoranti e meno spesa' },
      esperienze: { min: 500, max: 950, note: 'Più attività organizzate' },
    },
    total: { min: 5750, max: 9300 },
  },
  coccola: {
    name: 'Coccola',
    description: 'Hotel top, spa premium, più tour e poca attenzione al budget',
    total: { min: 9000, max: 15000 },
  },
};

export const practicalInfo = {
  car: {
    title: 'Auto a Noleggio',
    recommendations: [
      '2WD sufficiente per questo itinerario: niente Highlands e niente F-roads.',
      'Automatico consigliato per guidare rilassati.',
      'Agosto è alta stagione: meglio prenotare molto in anticipo.',
      'Questo piano privilegia Route 1 e strade asfaltate facili da guidare.',
      'Ultima notte vicino a KEF molto consigliata con il volo delle 08:20.',
    ],
    companies: ['Blue Car Rental', 'Lotus', 'Geysir', 'Northbound'],
  },
  safety: {
    title: 'Sicurezza Anti-Vertigini',
    tips: [
      '✓ Evitati Westfjords, Highlands e F-roads.',
      '✓ Restare su viewpoint larghi e protetti quando possibile.',
      '✓ Saltare senza problemi Dyrhólaey o i bordi più esposti di Snæfellsnes.',
      '✓ Spezzare le tratte lunghe rende l’itinerario molto più sostenibile.',
      '⚠️ Reynisfjara: mai avvicinarsi all’acqua e mai voltarsi di spalle al mare.',
    ],
  },
  packing: {
    title: 'Cosa Portare',
    essential: [
      'Giacca impermeabile e antivento',
      'Scarpe impermeabili con buon grip',
      'Strati termici',
      'Costume da bagno',
      'Occhiali da sole',
      'Powerbank',
      'Snack e borraccia',
      'Farmaci personali e cerotti',
    ],
  },
  apps: {
    title: 'App Utili',
    list: [
      { name: 'Vedur.is', description: 'Meteo ufficiale islandese' },
      { name: 'Road.is', description: 'Condizioni stradali in tempo reale' },
      { name: 'SafeTravel', description: 'Aggiornamenti sicurezza e consigli utili' },
      { name: '112 Iceland', description: 'App emergenze' },
      { name: 'Google Maps offline / Maps.me', description: 'Navigazione con mappe salvate' },
    ],
  },
  references: {
    title: 'Fonti esterne',
    list: [
      {
        name: 'Iceland\'s Ring Road',
        url: 'https://www.visiticeland.com/article/the-ring-road/',
      },
      {
        name: 'Driving in Iceland in August: A Complete Guide',
        url: 'https://guidetoiceland.is/best-of-iceland/driving-in-iceland-in-august-a-comprehensive-guide',
      },
    ],
  },
};

export const experiencesDatabase = [
  {
    id: 'sky-lagoon',
    name: 'Sky Lagoon',
    category: 'Lagune Termali',
    image: 'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=800&h=500&fit=crop',
    prices: [
      { type: 'Saman Pass', price: 13990, currency: 'ISK', eur: 93 },
      { type: 'Sér Pass', price: 19990, currency: 'ISK', eur: 133 },
    ],
    description:
      'Laguna moderna con vista oceano, più vicina a Reykjavík e comoda per chi vuole relax senza allungare troppo.',
    pros: ['Vicino a Reykjavík', 'Molto rilassante', 'Ottima vista oceano'],
    cons: ['Meno iconica della Blue Lagoon'],
    booking: 'Prenotazione consigliata',
    website: 'https://www.skylagoon.com',
  },
  {
    id: 'blue-lagoon',
    name: 'Blue Lagoon',
    category: 'Lagune Termali',
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&h=500&fit=crop',
    prices: [{ type: 'Comfort', price: 11990, currency: 'ISK', eur: 80 }],
    description:
      'La laguna termale più famosa d’Islanda, iconica e fotogenica, ma più turistica rispetto ad alternative vicine a Reykjavík.',
    pros: ['Esperienza iconica', 'Molto fotogenica', 'Facilities eccellenti'],
    cons: ['Più affollata', 'Meno agile con arrivo serale'],
    booking: 'Prenotazione obbligatoria',
    website: 'https://www.bluelagoon.com/is?utm_medium=gmb&utm_content=cta',
  },
  {
    id: 'jokulsarlon',
    name: 'Jökulsárlón & Diamond Beach',
    category: 'Ghiacciai',
    image: 'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&h=500&fit=crop',
    prices: [
      { type: 'Accesso', price: 0, currency: 'ISK', eur: 0 },
      { type: 'Boat tour indicativo', price: 6000, currency: 'ISK', eur: 40 },
    ],
    description:
      'Laguna glaciale e spiaggia nera ghiacciata: il grande highlight del viaggio, accessibile e spettacolare.',
    pros: ['Tra i luoghi più belli del viaggio', 'Molto adatto anti-vertigini', 'Visita semplice'],
    cons: ['Richiede guidare fino a est'],
    booking: 'Boat tour facoltativo, meglio prenotare',
    website: 'https://icelagoon.is/',
  },
  {
    id: 'kirkjufell',
    name: 'Kirkjufell',
    category: 'Snæfellsnes',
    image:
      'https://images.openai.com/static-rsc-4/B-F1jvTSwzA04eZKZmtZkAp7T8Y8_r2Q89wH8qES8MzNwbupHDde5w6oBFVlsJCz6S8ULl29VtKUBYOnl3SyiskO0nlsKuZt76ed-AsWhPA0-Em3luM6-_CAlCjcadv6kGjxPUdKm0U1E384Shl9tUC2Q6UKjRvLbM5oO1oc9TP81KiCOCmFJXLdqVC0FjKp?purpose=fullsize',
    prices: [{ type: 'Stop fotografico', price: 0, currency: 'ISK', eur: 0 }],
    description:
      'La montagna più iconica e fotografata d’Islanda, perfetta per uno stop semplice e spettacolare.',
    pros: ['Molto scenografica', 'Facile da visitare', 'Stop rapido e appagante'],
    cons: ['Molto popolare in alta stagione'],
    booking: 'Nessuna prenotazione',
    website: 'https://guidetoiceland.is/travel-iceland/drive/kirkjufell',
  },
  {
    id: 'arnarstapi',
    name: 'Arnarstapi',
    category: 'Snæfellsnes',
    image:
      'https://images.openai.com/static-rsc-4/4178Fc9LVMmbXCSd8qojkulFDzae1RUXnCGTHk_R2bTLqnO6dfZ0L1BTrlb52IrWuOXP62o9iPG9mrmj1kwnNxHsX77yKvpIj7bm4h_Ch-Spm-TUDy46XNWZEjUOHBPSMkMMSPbW8qPK7vZgvsEEn90CSiDE44jwMXUdVMKlhEVEvjsXj2XW43jt99Fy-zM6?purpose=fullsize',
    prices: [{ type: 'Stop panoramico', price: 0, currency: 'ISK', eur: 0 }],
    description:
      'Villaggio costiero con archi di roccia e sentieri scenografici: molto bello anche limitandosi alle parti più comode.',
    pros: ['Costa spettacolare', 'Passeggiata modulabile', 'Molto fotografico'],
    cons: ['Con vento forte alcuni tratti possono non essere piacevoli'],
    booking: 'Nessuna prenotazione',
    website: 'https://guidetoiceland.is/travel-iceland/drive/arnarstapi',
  },
  {
    id: 'budakirkja',
    name: 'Búðakirkja',
    category: 'Snæfellsnes',
    image:
      'https://images.openai.com/static-rsc-4/296U8xPGsODpjEHllsHPRjWdNo5cVI3qO0cLlfISDh3NpV3VpsVgglUblDU-jyLNOZIPug33g2mYO988eCbPuF1oLFZVZOS0Lv77TWLqMgB8XOhGOwbfgzbOmVHKRGX0cwu9qq2T5o9fgj6q9Eq35sJp5d4OdOZW_4JMIq_i9zoUMwZzRBor7fP0m7-bvTPV?purpose=fullsize',
    prices: [{ type: 'Stop fotografico', price: 0, currency: 'ISK', eur: 0 }],
    description:
      'La famosa chiesa nera di Búðir: una sosta breve ma elegantissima, perfetta da inserire senza stress.',
    pros: ['Sosta brevissima', 'Molto scenografica', 'Facile accesso'],
    cons: ['È soprattutto un photo stop'],
    booking: 'Nessuna prenotazione',
    website: 'http://www.budakirkja.is/',
  },
  {
    id: 'djupalonssandur',
    name: 'Djúpalónssandur',
    category: 'Snæfellsnes',
    image:
      'https://images.openai.com/static-rsc-4/4m7UkNYlqNkI-6AZXbCkh_4JEEBOtF0N5EiIZtOz8GlI1NSAY0iSeOkZsoGFbeEYXwu1QigVBAmt2a-uJiQiTARFP2bV9pXBGOK9q9z0H1-rbYSB-C5cfet76rmdf4C6RD43IEcI_Lb3II31YTHjQN528mMWkKLewbfF7GhO1LsY3n7R1pgFaka2Uq5ixwrV?purpose=fullsize',
    prices: [{ type: 'Accesso', price: 0, currency: 'ISK', eur: 0 }],
    description:
      'Spiaggia vulcanica nera con rocce, relitti e atmosfera quasi lunare.',
    pros: ['Scenario unico', 'Molto fotografica', 'Diversa dal resto del viaggio'],
    cons: ['Terreno un po’ irregolare in alcuni punti'],
    booking: 'Nessuna prenotazione',
    website: 'http://www.snaefellsjokull.com/djupalonssandur/',
  },
];

export const attractions = [
  {
    name: 'Thingvellir National Park',
    coordinates: { lat: 64.2558, lng: -21.1292 },
    type: 'Parco nazionale / UNESCO',
    description: 'Uno dei tre grandi classici del Golden Circle.',
    highlights: ['Placche tettoniche', 'Sentieri ampi', 'Molto adatto anti-vertigini'],
    accessibility: 'Ottima',
    time: '1–2 ore',
  },
  {
    name: 'Gullfoss Falls',
    coordinates: { lat: 64.3271, lng: -20.1211 },
    type: 'Cascata',
    description: 'La grande cascata simbolo del Golden Circle.',
    highlights: ['Vista iconica', 'Belle piattaforme', 'Molto scenografica'],
    accessibility: 'Buona',
    time: '45–60 min',
  },
  {
    name: 'Skógafoss',
    coordinates: { lat: 63.5321, lng: -19.5114 },
    type: 'Cascata',
    description: 'Una delle cascate più spettacolari del sud.',
    highlights: ['Vista dalla base', 'Arcobaleni', 'Stop semplice'],
    accessibility: 'Ottima dalla base',
    time: '30–45 min',
  },
  {
    name: 'Reynisfjara Beach',
    coordinates: { lat: 63.4042, lng: -19.0445 },
    type: 'Spiaggia nera',
    description: 'Basalto, faraglioni e sabbia vulcanica: uno dei luoghi più iconici del paese.',
    highlights: ['Colonne di basalto', 'Faraglioni', 'Scenografia potentissima'],
    accessibility: 'Buona ma con prudenza',
    time: '30–60 min',
    warning: 'Sneaker waves: distanza di sicurezza obbligatoria dal mare.',
  },
  {
    name: 'Jökulsárlón',
    coordinates: { lat: 64.0489, lng: -16.1798 },
    type: 'Laguna glaciale',
    description: 'Iceberg galleggianti e grande atmosfera artica.',
    highlights: ['Laguna', 'Possibili foche', 'Accessibilità alta'],
    accessibility: 'Perfetta',
    time: '1–2 ore',
  },
  {
    name: 'Diamond Beach',
    coordinates: { lat: 64.0442, lng: -16.1788 },
    type: 'Spiaggia glaciale',
    description: 'Ghiaccio trasparente sulla sabbia nera.',
    highlights: ['Contrasto unico', 'Foto bellissime', 'Passeggiata semplice'],
    accessibility: 'Perfetta',
    time: '30–45 min',
  },
  {
    name: 'Kirkjufell',
    coordinates: { lat: 64.9267, lng: -23.3065 },
    type: 'Montagna iconica',
    description: 'La montagna simbolo di Snæfellsnes.',
    highlights: ['Foto celebre', 'Facile accesso', 'Stop breve'],
    accessibility: 'Ottima',
    time: '20–40 min',
  },
  {
    name: 'Arnarstapi',
    coordinates: { lat: 64.7686, lng: -23.6207 },
    type: 'Villaggio costiero',
    description: 'Costa lavica e archi di roccia, ma visitabili con approccio prudente.',
    highlights: ['Archi naturali', 'Costa drammatica', 'Percorso modulabile'],
    accessibility: 'Buona scegliendo i tratti comodi',
    time: '30–60 min',
  },
];
